#!/bin/bash

echo "Installing dots..."

git clone https://github.com/Harmelodic/dots.git "$HOME/dots" -q
cp "$HOME/dots/vars.example" "$HOME/dots/vars"

if [[ "$(uname)" =~ "Darwin" ]]; then
    {
        echo ""
        echo "# dots"
        echo "source ~/dots/rc"
    } >> "$HOME/.bash_profile"

    {
        echo ""
        echo "# dots"
        echo "source ~/dots/rc"
    } >> "$HOME/.zshrc"
elif [[ "$(uname)" =~ "Linux" ]]; then
    {
        echo ""
        echo "# dots"
        echo "source ~/dots/rc"
    } >> "$HOME/.bashrc"

    {
        echo ""
        echo "# dots"
        echo "source ~/dots/rc"
    } >> "$HOME/.zshrc"
else
    echo ""
    echo "ERROR! Unsupported System: $(uname)"
    echo "Please add the following line to your .bashrc / .bash_profile / .zshrc file in your home directory:"
    echo ""
    echo "source ~/dots/rc"
    echo ""
fi

echo "Done. - Terminal refresh required";

echo ""
echo "Set up your personal dots-related vars by editing:"
echo "$HOME/dots/vars"
echo ""