#!/bin/bash

echo "Installing dots..."

echo "Cloning..."
git clone https://gitlab.com/Harmelodic/dots.git $HOME/dots -q

cp $HOME/dots/vars.example $HOME/dots/vars

echo "Setting up source..."
if [[ "$(uname)" =~ "Darwin" ]]; then
    echo "" >> $HOME/.bash_profile
    echo "# dots" >> $HOME/.bash_profile
    echo "source dots/bashrc" >> $HOME/.bash_profile
else
    echo ""
    echo "ERROR! Unsupported System: $(uname)"
    echo "Please add the following line to your .bashrc / .bash_profile file in your home directory:"
    echo ""
    echo "source dots/bashrc"
    echo ""
fi

echo "Install Complete. - Terminal refresh required";

echo ""
echo "Set up your personal dots-related vars by editing:"
echo "$HOME/dots/vars\n"
echo ""