#!/bin/bash

export DOTS=~/dots

if [[ "$(uname)" =~ "Darwin" ]]; then
    # PS1="%n@%m %1~ $ " # name@machine directory $
    PS1="%1~ $ " # directory $
elif [[ "$(uname)" =~ "Linux" ]]; then
    PS1="\[\033[01;32m\]\u@\h\[\033[01;37m\] \W\[\033[01;32m\] \$\[\033[00m\] "
fi

# Custom commands
export PATH="${DOTS}/bin:${PATH}"

# Custom sourced commands
for file in "$DOTS/source-bin/"* ; do
    if [ -f "$file" ] ; then
        # shellcheck disable=SC1090
        source "$file"
    fi
done

# Make the command line have Vi functionality
# set -o vi

# General Aliases
alias spy='watch ' # Gets watch to support aliases with spy
alias ll='ls -lh'
alias la='ls -lah'

# Git
git config --global core.excludesfile $DOTS/config-files/.gitignore
git config --global core.editor vim
git config --global core.ignorecase true
git config --global gpg.program gpg
git config --global pull.rebase false
git config --global init.defaultBranch main
git config --global push.autoSetupRemote true
export GPG_TTY=$(tty)

if [[ "$(uname)" =~ "Darwin" ]]; then
    git config --global credential.helper osxkeychain # Permanent cache
elif [[ "$(uname)" =~ "Linux" ]]; then
    git config --global credential.helper 'cache --timeout=86400' # 24 hour cache
fi

# Kubectl
alias k='kubectl'
export PATH="${HOME}/.krew/bin:${PATH}"
alias kx='kubectl ctx'
alias portargo='kubectl -n argocd port-forward svc/argo-cd-argocd-server 9999:80'
export USE_GKE_GCLOUD_AUTH_PLUGIN=True

# Kubectl Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Lima VM
if [[ "$(uname)" =~ "Darwin" ]]; then
    alias cn='lima nerdctl'
fi

# SDKMAN
export SDKMAN_DIR="${HOME}/.sdkman"
[[ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ]] && source "$SDKMAN_DIR/bin/sdkman-init.sh"

# Google Cloud SDK
export GOOGLE_CLOUD_SDK="${HOME}/google-cloud-sdk"
if [ -f "$GOOGLE_CLOUD_SDK/path.zsh.inc" ]; then source "$GOOGLE_CLOUD_SDK/path.zsh.inc"; fi
if [ -f "$GOOGLE_CLOUD_SDK/completion.zsh.inc" ]; then source "$GOOGLE_CLOUD_SDK/completion.zsh.inc"; fi

# Node Version Manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Android SDK & Platform Tools
if [[ "$(uname)" =~ "Darwin" ]]; then
    export ANDROID_HOME="$HOME/Library/Android/sdk"
elif [[ "$(uname)" =~ "Linux" ]]; then
    export ANDROID_HOME="$HOME/Android/Sdk"
fi
export PATH="$ANDROID_HOME/platform-tools:$PATH"
