#!/bin/bash

export DOTS=~/dots

if [[ "$(uname)" =~ "Darwin" ]]; then
    # PS1="%n@%m %1~ $ " # name@machine directory $
    PS1="%1~ $ " # directory $
elif [[ "$(uname)" =~ "Linux" ]]; then
    PS1="\[\033[01;32m\]\u@\h\[\033[01;37m\] \W\[\033[01;32m\] \$\[\033[00m\] "
fi

# Custom utility commands
PATH="${DOTS}/utils:${PATH}"
export PATH

# Custom source utility commands
for file in $DOTS/source-utils/* ; do
    if [ -f "$file" ] ; then
        source "$file"
    fi
done

# Make the command line have Vi functionality
set -o vi

# Aliases
alias ll='ls -lh'
alias la='ls -lah'
alias k='kubectl'

# Git
git config --global core.excludesfile $DOTS/config-files/.gitignore
git config --global core.editor vim
git config --global core.ignorecase true
git config --global gpg.program gpg
GPG_TTY=$(tty)
export GPG_TTY

if [[ "$(uname)" =~ "Darwin" ]]; then
    git config --global credential.helper osxkeychain # Permanent cache
elif [[ "$(uname)" =~ "Linux" ]]; then
    git config --global credential.helper 'cache --timeout=86400' # 24 hour cache
fi
