#!/bin/bash

# Performs a git clone, then jumps straight into the directory after cloning

clone() {
	git clone "$1"
	# shellcheck disable=SC2012
	new_directory=$(ls -at1 | head -1)
	cd "$new_directory" || exit
}
