#!/bin/bash

# Make a directory then immediately jump into it

mkcd() {
	directory=$1

	if [ -z "$directory" ]; then
		echo "No argument given."
	elif [ -d "$directory" ]; then
		echo "Directory already exists."
	else
		mkdir "$directory"
		cd "$directory" || exit
	fi
}
