#!/bin/bash

# Make a directory then immediately jump into it

mkcd () {
    if [ -z "$1" ]; then
        echo "No argument given."
    elif [ -d "$1" ]; then
        echo "Directory already exists."
    else
        mkdir "$1"
        cd "$1" || exit
    fi
}