#!/bin/bash

# Management tool for dots 

if [[ $1 == "upgrade" ]]; then
    echo "Upgrading... $(cd $DOTS && git pull -q)"
    dots -v
elif [[ $1 == "" || $1 == "help" || $1 == "-h" || $1 == "-help" || $1 == "--help" ]]; then
    echo "Please provide a dots command."
    echo ""
    echo "$ dots <command>"
    echo ""
    echo "Where <command> is one of the following:"
    echo ""
    echo "- help (-h) (--help)"
    echo "- list"
    echo "- upgrade"
    echo ""
elif [[ $1 == "version" || $1 == "-v" || $1 == "-version" || $1 == "--version" ]]; then
    echo $(cd $DOTS && git rev-parse HEAD)
elif [[ $1 == "list" || $1 == "ls" ]]; then
    echo "dots can do:"
    echo ""
    echo "<TODO>"
else
    echo "Unrecognised dots command: $1";
fi
