#!/bin/bash

# Prunes all branches that have been merged into the master branch. Stands for: Git Prune Local Repo

git remote prune origin
git branch --merged | grep -vE "(^\*|master)" | xargs git branch -d