#!/bin/bash

# Specify version of Java to use - relies on SDKMAN


if [[ "$(uname)" =~ "Darwin" ]]; then
    . ~/.sdkman/bin/sdkman-init.sh
    IDENTIFIER=`sdk list java | grep installed | grep $1 | grep hs-adpt | awk '{print $NF}'`
    sdk default java $IDENTIFIER
else
    echo "Command not supported on non-macOS system"
fi
