#!/bin/bash

# Outputs the current/new versions & packages installed on current machine

# OS Specific
if [[ "$(uname)" =~ "Darwin" ]]; then
    # Mac specific upgrades
    echo -e "\n--- BREW ---"
    brew -v

    echo -e "\n--- BREW FORMULAE---"
    brew list

    echo -e "\n--- BREW CASK FORMULAE ---"
    brew cask list

    echo -e "\n--- SDKMAN ---"
    [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk version | xargs -I {} echo "{}"

    echo -e "\n--- SDKMAN CANDIDATES: ---"
    sdk current | xargs -I {} echo "{}"
else
    echo -e "\nNo OS Specific updates to install for $(uname)"
fi

# OS Agnostic
echo -e "\n--- GCLOUD ---"
gcloud version | head -1

echo -e "\n--- NPM GLOBAL MODULES ---"
npm ls -g --depth=0

echo -e "\n--- RUST ---"
rustup -V
rustc -V

echo -e "\n--- DOTS ---"
dots version