#!/bin/bash

# Runs the update/upgrade commands on package managers & tools, then outputs the current/new versions

# OS Specific
if [[ "$(uname)" =~ "Darwin" ]]; then
    # Mac specific upgrades
    echo -e "\n--- BREW ---"
    brew update
    brew -v

    echo -e "\n--- BREW FORMULAE---"
    brew upgrade
    brew list

    echo -e "\n--- BREW CASK FORMULAE ---"
    brew cask upgrade
    brew cask list

    echo -e "\n--- GCLOUD ---"
    gcloud components update --quiet
    gcloud version | head -1

    echo -e "\n--- RUST ---"
    rustup update
    rustup -V
    rustc -V

    echo -e "\n--- SDKMAN ---"
    [[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
    sdk selfupdate
    sdk version | xargs -I {} echo "{}"

    echo -e "\n--- SDKMAN CANDIDATES: ---"
    sdk upgrade 
    sdk current | xargs -I {} echo "{}"
elif [[ "$(uname -a)" =~ "MANJARO" ]]; then
    # Manjaro specific upgrades
    echo -e "\n--- PACMAN PACKAGES: ---"
    sudo pacman -Syu
else
    echo -e "\nNo OS Specific updates to install for $(uname)"
fi

# OS Agnostic
echo -e "\n--- NPM GLOBAL MODULES ---"
npm up -g
npm ls -g --depth=0

echo -e "\n--- DOTS ---"
dots upgrade