#!/bin/bash

# WHAT IS MY CONFIG
echo ""


echo ""
echo "git"
echo "------------------------------------"
git config --list | grep -v alias
echo ""
echo ""



echo ""
echo "gcloud"
echo "------------------------------------"
gcloud config list
echo ""
echo ""



echo ""
echo "aws"
echo "------------------------------------"
aws configure list
echo ""
echo ""



echo ""
echo "kubectl"
echo "------------------------------------"
kubectl config current-context
echo ""
echo ""