#!/bin/bash

# WHAT IS MY CONFIG
echo ""


echo ""
echo "sdk"
echo "------------------------------------"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk current | xargs -I {} echo "{}"
echo ""
echo ""


echo ""
echo "git"
echo "------------------------------------"
git config --list | grep -v alias
echo ""
echo ""


echo ""
echo "gcloud"
echo "------------------------------------"
gcloud config list
echo ""
echo ""



echo ""
echo "aws"
echo "------------------------------------"
aws configure list
echo ""
echo ""



echo ""
echo "kubectl"
echo "------------------------------------"
kubectl config current-context
echo ""
echo ""