[tools]
"aqua:txn2/kubefwd" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }
checkov = "latest"
conftest = "latest"
gcloud = "latest"
go = "latest"
golangci-lint = "latest"
gradle = "latest"
helm = "latest"
java = "temurin-25"
jq = "latest"
k9s = "latest"
kubectl = "latest"
kustomize = "latest"
markdownlint-cli2 = "latest"
maven = "latest"
mongosh = "latest"
node = "latest"
opa = "latest"
opentofu = "latest"
pipx = "latest"
poetry = "latest"
postgres = "latest"
prettier = "latest"
python = "latest"
redis = "latest"
regal = "latest"
ruff = "latest"
skaffold = "latest"
spectral = "latest"
terraform = "latest"
terragrunt = "latest"
tflint = "latest"
yamllint = "latest"
yarn = "latest"
yq = "latest"

[settings]
idiomatic_version_file_enable_tools = ["terraform", "node", "python", "java", "go", "opentofu"]
experimental = true
